<!DOCTYPE html>
<html>
      <head>  
        <meta charset="utf-8"/>
        <title> ItNut</title>
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="css/style.css">
       
    
   
        
        

            <script src="bootstrap/js/jquery.js"></script>
            <script src="bootstrap/js/bootstrap.min.js"></script>

        
            

        <nav class="navbar navbar-fixed-left navbar-minimal animate" role="navigation">
        <div class="navbar-toggler animate">
            <span class="menu-icon"></span>
        </div>
        <ul class=" navbar-menu animate">
                <li><a href="#">Home</a></li>
                <li ><a href="#">Profile</a></li>
                <li ><a href="#">Messages</a></li>
                
                <li><a href="#">Home</a></li>
                <li ><a href="#">Profile</a></li>
                <li ><a href="#">Messages</a></li>
            
        </ul>
</nav>

    </head>
    <body>
       


<p> Bienvenue chez ItNut !!! </p>

<p>
    <img src="images/devenez.jpg" alt="Photo" title="!" >
</p>

    
  </body>

</html>
