<!DOCTYPE html>
<html>
      <head>  
        <meta charset="utf-8"/>
        <title> ItNut</title>
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="css/index.css">
            <script src="bootstrap/js/jquery.js"></script>
            <script src="bootstrap/js/bootstrap.min.js"></script>

        
            
     </head> 
    <body>
       <div id="bloc_page">
            <header>
                <div id="titre_principal">
                        logo

                <h1>ItNut</h1>
                <h2> Bienvenue chez ItNut !!! </h2>
        </div>

         <nav>
            <ul>
                <li ><a href="boutique.html"> Boutique </a></li> 
            </ul>
        </nav>
            </header>


        <div id="banniere_image">
             <img src="images/devenez.jpg" alt="Photo" title="!" >
        </div>    
       
    
    </body>

</html>
